version: "3.9"
services:
  server:
    build: ./server
    container_name: vestibleX_server
    volumes:
      - .server:/server
      - /server/node_modules
  client:
    build: ./client
    container_name: vestibleX_client
    stdin_open: true
    tty: true
